name: car
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.9.7
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - imageio
    - pip:
        - moviepy
        - tensorflow-gpu
        - keras
        - python-engineio==3.13.2
        - python-socketio==4.6.1
        - opencv-python